### ISSUE TITLE
form horizontal JSF2.3 not working on MyFaces 2.3

### ISSUE THREAD

**Issue by cavalka** [TheCoder4eu/BootsFaces-OSP#1039]
The form component is not rendering attributes correctly.  Any attributes overridden/new(styleClass,etc) are not displaying in rendered output html.  I am using JSF2.3/ominifaces 3.2/primefaces6.2/open liberty server.  Any attributes not explicitly specified in Form component(id,etc) work fine...they display in output html.

**Comment by sometowngeek** [comment]
@cavalka Can you please show the **Minimal, complete, and verifiable example (MCVE)**?

I think I might be able to help you out as I struggled a little bit with this before.

**Comment by cavalka** [comment]
@sometowngeek Below is example documentation.  You will notice the form-horizontal class is missing from the form html tag.  Thanks for any help in advance.

Sample web page:
![sample webpage](https://user-images.githubusercontent.com/18357624/49591885-4621c000-f935-11e8-9e54-122caf631c1f.png)
Sample html output:
![sample html output](https://user-images.githubusercontent.com/18357624/49591908-546fdc00-f935-11e8-8203-3057d0731b9a.png)
Sample source code:
![sample source code](https://user-images.githubusercontent.com/18357624/49592239-32c32480-f936-11e8-84e5-3e56daf92b45.png)

**Comment by stephanrauh** [comment]
Dear @cavalka ,

first of all, welcome to GitHub in general and to BootsFaces in particular! This seems to be your first issue. Thanks for reaching out to us!

When @sometowngeek mentioned a "reproducer", they hoped for something allowing us to reproduce your bug in virtually no time. You know, BootsFaces is a hobbyist project. Everything we do is done in our leisure time. From this point of view, your screenshots are great because they probably allow us to reproduce your bug. However, reproducing your bug is a lot easier if you provide us the code as text we can simply copy.

If you really want to do us a favor, create a GitHub repository we can simply clone and run. I know that's demanding a lot. I went through this process a couple of times myself, and I know it's frustrating, not to say infuriating. I can't tell how many times it turned out that the bug was on my side... but even in this case, we'd like to hear from you, because your experience might help the greater BootsFaces community.

That said, I'm looking forward either to your reproducer, or to the answer of you, @sometowngee!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
In the meantime, I've been trying to reproduce your bug. Your code sample doesn't that many attributes in the `b:form` widget. What am I missing?

I've generated a demo with a regular attribute (`style´) and a pass-through attribute (`class`). Both attributes work like charm:

```xml
    <style>
    .some-class {
    	color:white;
    }
    </style>
    <b:form style="background-color:black" pt:class="some-class">
    This is a demo form.
    </b:form>
````

Resulting page:
![image](https://user-images.githubusercontent.com/3045767/49613413-d7ca1580-f9a7-11e8-81aa-0280a5f3b7ad.png)

Doesn't look that wrong, does it? Obviously, I've missed something?

As for style-class, judging from the source code I believe this attribute works, too. However, this is the only attribute with a special treatment, so it may be a potential source of errors.

**Comment by stephanrauh** [comment]
After reading your issue another time, I wonder if you're reporting something entirely different. I assumed you've added an attribute to `b:form`, and it wouldn't render. However, you're mentioning you're missing `class="form-horizontal"` in conjunction with `<b:form horizontal="true">`.

Side remark: `horizontal="true"` works fine on my machine. Sigh!

**Comment by sometowngeek** [comment]
In addition to what @stephanrauh suggested, you could post a gist. See [Github's Gist](https://gist.github.com/). You can post multiple files there and they all show in the same page. Make sure to assign appropriate extensions on the file names, then the markdown will render appropriate color coding.

**Comment by cavalka** [comment]
My issue is in either net.bootsfaces.component.form.Form or net.bootsfaces.component.form.FormCore.  I am able to run thru debugger and it executes net.bootsfaces.component.form.Form.getSyleClass() method and assigns the form-horizontal class, but that value gets lost somewhere after that point and never makes it back to html rendering.  This is first time exploring bootfaces and I am new to JSF and CDI, so it definitely could be something in my setup.  I am just wonder if it has something to do with JSF2.3 version and CDI2.0.  I am using IBM openliberty server that uses JSF2.3 myfaces implementation and CDI2.0.  This form component looks to be the only component that doesn't extend CoreRenderer.  All the other components that use extend CoreRenderer work fine.

**Comment by sometowngeek** [comment]
@cavalka, Where are you assigning the class to the form? I don't see it anywhere in the .xhtml file.

I would do something like this if you wanted to do it on the xhtml page.
```
<b:form style-class="form-horizontal">

<%-- this works, too --%>
<b:form styleClass="form-horizontal">
```

Given your CSS rule is:
```
form-horizontal{
    // properties:values;
}
```

Or... maybe from what you just said, it sounds like you are trying to do it in java. Which approach are you trying to take?

Again, please provide a code snippet we can copy/paste to reproduce (either in Github or gist).

**Comment by cavalka** [comment]
BootFaces assigns the class for
`<b:form  horizontal="true">`
This is done in net.bootsfaces.component.form.Form
`/**
	 * Inline style of the input element.
	 * <P>
	 * 
	 * @return Returns the value of the attribute, or null, if it hasn't been
	 *         set by the JSF file.
	 */
	public String getStyleClass() {
		String clazz = super.getStyleClass();
		if (isHorizontal()) {
			if (clazz == null) {
				clazz = "form-horizontal";
			} else {
				clazz += " form-horizontal";
			}
		}
		if (isInline()) {
			if (clazz == null) {
				clazz = "form-inline";
			} else {
				clazz += " form-inline";
			}
		}
		return clazz;
	}`

This gets assigned, but the assignment is lost at some point after this event.  

I don't think providing additional code will be able to help assist.  If you have a basic horizontal-form tag 
code as provided in examples that is basically what I use(as seen in screenshot above).  

I think that code needs to be tested using open liberty and J2EE8 setup to replicate my issue.  Does Bootfaces work with JSF2.3?  I noticed the following on website.

**BootsFaces is targeted at Java EE 6/7 and requires a Java 1.6 or later VM. 

JSF 2.0, 2.1 and 2.2 are supported.**

**Comment by sometowngeek** [comment]
**Hint**: triple back ticks "`" (the key to the left of number 1 key) will allow multi-line code. Just have to make sure to open and close the code block with ```. See the code example in [Github's markdown page](https://guides.github.com/features/mastering-markdown/)

Oh... I get what you're saying now.

It sounds like the CSS may be the problem. In CSS, it's always **last rule first.**

Like so:
### thisFile.css
```css
.thisRule {
  color: #F00;
}
```

### thatFile.css
```css
.thisRule {
  color: #00F;
}
```

### index.html
```html
<body>
<link rel="stylesheet" href="thisFile.css" />
<link rel="stylesheet" href="thatFile.css" />

<!-- Guess which color this is. -->
<p class="thisRule">Hello!</p>
```

It ends up being blue because the last rule dictated that the color is blue (`#00F`) and thatFile.css is the last CSS file being loaded. (Assuming no in-line code overrides this).

So... I wonder where the new CSS rule is placed. Are you placing it in the body with `<h:outputStyle ... >`?
Just in case: [How to use <h:outputStyle>](https://www.tutorialspoint.com/jsf/jsf_outputstylesheet_tag.htm)

**Comment by stephanrauh** [comment]
@cavalka You're right, `b:form` does not use the `CoreRenderer`. JSF components often consist of two parts, the component class and the renderer class. In the case of `b:form`, we simply use the renderer of the base class (i.e. `h:form`).

All we want to do is to add the CSS class `form-inline` or `form-horizontal`, so it suffices to -highjack- overload the `getStyleClass()` method and add some custom code to it.

@sometowngeek It seems both of us got the question wrong. It's not about passing a user-defined CSS class. It's about BootsFaces failing to render a CSS class it promises to render.

**Comment by stephanrauh** [comment]
@cavalka As for JSF 2.3: BootsFaces 1.4.0 is the first version fully compatible to Mojarry 2.3. I didn't text MyFaces 2.3 yet, so I can say little about that yet.

In theory, there's no reason why BootsFaces <= 1.3.x wasn't compatible to JSF 2.3. Unfortunately, the Mojarra programmers introduced something  weird. It's not exactly a bug, because there's no difference as long as you generate correct HTML code. But closing the HTML tags in the wrong order usually works fine in Mojarra <= 2.2, but renders a broken page in Mojarra 2.3.

So we've fixed our HTML code, and I recommend using BootsFaces 1.4.0-SNAPSHOT unless you're going to production any time soon. We plan to publish BootsFaces 1.4.0 really soon now (but I'm already saying this for weeks, and there's always a reason to delay the shipment) :).

**Comment by stephanrauh** [comment]
@cavalka I've tried to start our showcase on Open Liberty 18.0.3, but it's broken. Did you already run into the error message?

```
ERROR   ] SRVE0777E: Excepción lanzada por la clase de aplicación 'javax.faces.webapp.FacesServlet.service:236'
javax.servlet.ServletException: com/sun/faces/facelets/tag/MethodRule
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:236)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at [internal classes]
Caused by: java.lang.NoClassDefFoundError: com/sun/faces/facelets/tag/MethodRule
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.myfaces.view.facelets.tag.AbstractTagLibrary$UserComponentHandlerFactory.<init>(AbstractTagLibrary.java:558)
	... 1 more

[ERROR   ] SRVE0315E: Se ha producido una excepción: java.lang.Throwable: javax.servlet.ServletException: com/sun/faces/facelets/tag/MethodRule
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4998)
	at [internal classes]
Caused by: javax.servlet.ServletException: com/sun/faces/facelets/tag/MethodRule
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:236)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: com/sun/faces/facelets/tag/MethodRule
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.myfaces.view.facelets.tag.AbstractTagLibrary$UserComponentHandlerFactory.<init>(AbstractTagLibrary.java:558)
	... 1 more
```

**Comment by stephanrauh** [comment]
@cavalka Good news (of a sort): I've managed to reproduce the bug. Running my demo on Wildfly 14 generates the HTML code:

![image](https://user-images.githubusercontent.com/3045767/49698388-4cc56700-fbc3-11e8-9b10-dea2954a4707.png)

The same demo run on Open Liberty Version 18.0.0.3 with the JavaEE 8 profile drops both the `style`and the `class` attributes:

![image](https://user-images.githubusercontent.com/3045767/49698394-5e0e7380-fbc3-11e8-9e72-49e6c86deafe.png)

**Comment by stephanrauh** [comment]
As it turns out, MyFaces 2.3 doesn't render the attributes `style` and `styleClass`. Mojarra 2.3 renders both. 

@struberg @tandraschko Is this an unwanted incompatibility or an intended behaviour?

**Comment by cavalka** [comment]
@stephanrauh Try change the event listener in Form.java from PostAddToViewEvent to PreRenderViewEvent or PostRenderViewEvent.  I think PostRenderViewEvent is new in JSF2.3.  I'm not sure it will resolve the issue, but worth testing.  Thanks for digging into this issue.

**Comment by stephanrauh** [comment]
Thanks for the hint! Unfortunately, I don't think it'll solve the issue. You know, I relied on `getStyle()` and `getStyleClass()` being called in the `encodeBegin()` method. But I can't spot such a call in the MyFaces implementation. Nor can I spot a method call I can piggyback. Maybe the only solution is to implement our own `FormRenderer`, but that's a potential source of future incompatibilities, too.

Here's the relevant source code:

```java
    public void encodeBegin(FacesContext facesContext, UIComponent component)
            throws IOException
    {
        org.apache.myfaces.shared.renderkit.RendererUtils.checkParamValidity(facesContext, component, UIForm.class);

        UIForm htmlForm = (UIForm)component;

        ResponseWriter writer = facesContext.getResponseWriter();
        String clientId = htmlForm.getClientId(facesContext);
        String acceptCharset = getAcceptCharset(facesContext, htmlForm);
        String actionURL = getActionUrl(facesContext, htmlForm);
        String method = getMethod(facesContext, htmlForm);

        Map<String, List<ClientBehavior>> behaviors = null;
        if (component instanceof ClientBehaviorHolder)
        {
            behaviors = ((ClientBehaviorHolder) component).getClientBehaviors();
            if (!behaviors.isEmpty())
            {
                ResourceUtils.renderDefaultJsfJsInlineIfNecessary(facesContext, writer);
            }
        }
        
        writer.startElement(HTML.FORM_ELEM, htmlForm);
        writer.writeAttribute(HTML.ID_ATTR, clientId, null);
        writer.writeAttribute(HTML.NAME_ATTR, clientId, null);
        writer.writeAttribute(HTML.METHOD_ATTR, method, null);
        if (acceptCharset != null)
        {
            writer.writeAttribute(HTML.ACCEPT_CHARSET_ATTR, acceptCharset, null);
        }
        String encodedActionURL = facesContext.getExternalContext().encodeActionURL(actionURL);
        
        writer.writeURIAttribute(HTML.ACTION_ATTR,
                encodedActionURL,
                null);
        
        if (htmlForm instanceof ClientBehaviorHolder)
        {
            behaviors = ((ClientBehaviorHolder) htmlForm).getClientBehaviors();
            if (behaviors.isEmpty() && isCommonPropertiesOptimizationEnabled(facesContext))
            {
                CommonPropertyUtils.renderEventProperties(writer, 
                        CommonPropertyUtils.getCommonPropertiesMarked(htmlForm), htmlForm);
            }
            else
            {
                if (isCommonEventsOptimizationEnabled(facesContext))
                {
                    CommonEventUtils.renderBehaviorizedEventHandlers(facesContext, writer, 
                           CommonPropertyUtils.getCommonPropertiesMarked(htmlForm),
                           CommonEventUtils.getCommonEventsMarked(htmlForm), htmlForm, behaviors);
                }
                else
                {
                    HtmlRendererUtils.renderBehaviorizedEventHandlers(facesContext, writer, htmlForm, behaviors);
                }
            }
            if (isCommonPropertiesOptimizationEnabled(facesContext))
            {
                CommonPropertyUtils.renderCommonPassthroughPropertiesWithoutEvents(writer, 
                        CommonPropertyUtils.getCommonPropertiesMarked(component), component);
                HtmlRendererUtils.renderHTMLAttributes(writer, htmlForm, HTML.FORM_ATTRIBUTES);
            }
            else
            {
                HtmlRendererUtils.renderHTMLAttributes(writer, htmlForm, 
                        HTML.FORM_PASSTHROUGH_ATTRIBUTES_WITHOUT_EVENTS);
            }
        }
        else
        {
            if (isCommonPropertiesOptimizationEnabled(facesContext))
            {
                CommonPropertyUtils.renderCommonPassthroughProperties(writer, 
                        CommonPropertyUtils.getCommonPropertiesMarked(component), component);
                HtmlRendererUtils.renderHTMLAttributes(writer, htmlForm, HTML.FORM_ATTRIBUTES);
            }
            else
            {
                HtmlRendererUtils.renderHTMLAttributes(writer, htmlForm, HTML.FORM_PASSTHROUGH_ATTRIBUTES);
            }
        }

        writer.write(""); // force start element tag to be closed
```

**Comment by tandraschko** [comment]
can you provide a small reproducer, without bootsfaces? So i could create a unittest and check it.

**Comment by stephanrauh** [comment]
@tandraschko There you are: https://github.com/stephanrauh/FormClassAndStyleDemo

Now I'm really confused. Can you point out the line MyFaces generated the `style` and `class` attributes?

**Comment by tandraschko** [comment]
So, do you mean it's working as expected?

As far as i can see here (https://github.com/TheCoder4eu/BootsFaces-OSP/blob/master/src/main/java/net/bootsfaces/component/form/Form.java#L80), you just overwrite the getter and hope that the JSF impl uses the getter, right?

In MyFaces it's done here: https://github.com/apache/myfaces/blob/158c94e38a6dd9e1502af12bedbc061d9a5f93d1/impl/src/main/java/org/apache/myfaces/renderkit/html/base/HtmlFormRendererBase.java#L134

It uses the attribute map instead of getter/mapper, which is a normal way to render common attributes.
We also do it in PF with #renderPassThruAttributes(....)

**Comment by stephanrauh** [comment]
I see. Thanks!

Originally, BootsFaces read the values directly from the attribute map until we experience difficulties, especially with value expression which wouldn't compute to values. So we ruefully went back to using getters and believed everybody does so. :)

**Comment by stephanrauh** [comment]
I've tried to manipulate the attributemap in the PostAddToViewEvent. Unfortunately, this doesn't work. MyFaces has modified the FormRenderer too much. We'd have to call an internal class that keeps track how many attributes have been set.

I'm afraid we have to fork either the Mojarra `FormRenderer`(simple, but disallowed by the GPL license) or the MyFaces `HtmlFormRenderer` (much more sophisticated, but put under the liberal Apache V2 license). That's bad in that we don't benefit from further improvements automatically.

**Comment by tandraschko** [comment]
it should work fine if you do it in PreRenderComponent -> form.setStyleClass(form.getSTyleClass() + "blub"));

**Comment by stephanrauh** [comment]
I can't access ` _CommonPropertyConstants.markProperty()` from outside. And I can't simply derive the BootsFaces `Form` from `javax.faces.component.html.HtmlForm`. Or can I?

```java
    public void setStyleClass(String styleClass)
    {
        getStateHelper().put(PropertyKeys.styleClass, styleClass ); 
        _CommonPropertyConstants.markProperty(this, _CommonPropertyConstants.STYLECLASS_PROP);
    }
```

**Comment by stephanrauh** [comment]
Oh. To answer my own question: Yes, we can! Thomas, once again, thanks a lot! Now it works!

**Comment by stephanrauh** [comment]
As for simply extending `UIForm`: The MyFaces version bundled with Open Liberty Version 18.0.0.3 has some performance optimization. It doesn't render an attribute unless it has been marked in the `_CommonPropertyConstants` map. That's why the original approach didn't work.

Currently, I'm using the `PostAddToViewEvent` simply because it's already there. Do you recommend using `PreRenderComponentEvent` instead?

**Comment by tandraschko** [comment]
Prerendercomponent is always called, postaddtoview not. The handling is different in myfaces and mojarra. Even more different with myfaces viewpooling.

**Comment by stephanrauh** [comment]
Done and documented. Thanks everybody for your patience and for staying insistent!
