### ISSUE TITLE
b:selectOneMenu onchange does not work

### ISSUE THREAD

**Issue by weidingergerald** [TheCoder4eu/BootsFaces-OSP#244]
Hello all,

we are using BootsFaces v0.8.0 and used the provided selectOneMenu.

Since v0.8.0 it should be possible to use the AJAX functionality, but in our case, unfortunately, it does not work as expected.

When the onchange event is triggered we get the error message "Uncaught TypeError: BsF.ajax.callAjax is not a function".

Do you have an idea how this problem could be solved?

Regards, Gerald

**Comment by stephanrauh** [comment]
I've tried to understand and reproduce your error, but I failed. Can you send me a JSF file so I can reproduce the bug?

**Comment by stephanrauh** [comment]
Another idea: chances are I've already fixed the error. Can you try to run your code with BootsFaces-0.8.1-SNAPSHOT? See #151 on how to get it. 

Thanks in advance!
Stephan

**Comment by weidingergerald** [comment]
The code works with the BootsFaces-0.8.1-SNAPSHOT. Thank you very much for your efforts.

**Comment by stephanrauh** [comment]
So let's close the issue :).
